# Generated by Django 4.0.4 on 2022-06-04 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0005_post_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
