# Generated by Django 4.0.4 on 2022-07-03 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0007_imagepost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImagePost',
        ),
    ]
