# Generated by Django 4.0.5 on 2022-06-22 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0007_audio_store'),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record', models.FileField(upload_to='media/')),
            ],
            options={
                'db_table': 'Audio_store',
            },
        ),
        migrations.CreateModel(
            name='ImagePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='posts/%Y', verbose_name='Photo')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_post', to='first_app.post')),
            ],
        ),
        migrations.DeleteModel(
            name='Audio_store',
        ),
    ]
