# Generated by Django 4.0.5 on 2022-06-22 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0008_audiostore_imagepost_delete_audio_store'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AudioStore',
        ),
    ]
