# Generated by Django 4.0.4 on 2022-07-08 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0009_imagepost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagepost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='posts/', verbose_name='Photo'),
        ),
    ]
