# Generated by Django 4.0.6 on 2022-08-05 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0011_alter_imagepost_image_alter_imagepost_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagepost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='posts/', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='imagepost',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_post', to='first_app.post'),
        ),
    ]
