# Generated by Django 4.0.6 on 2022-08-05 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0013_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
