# Generated by Django 4.0.6 on 2022-08-05 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0014_remove_post_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagepost',
            options={},
        ),
    ]
