# Generated by Django 4.0.4 on 2022-06-06 17:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('first_app', '0006_delete_profile'),
        ('comments_app', '0002_comment_updated_at'),
        ('likes_app', '0002_alter_likecomment_user_alter_likepost_user'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='likecomment',
            unique_together={('user', 'like_comment')},
        ),
        migrations.AlterUniqueTogether(
            name='likepost',
            unique_together={('user', 'like_post')},
        ),
    ]
